spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mariadb://localhost:3306/ms-loja
    username: ygor
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
  cache:
    type: redis
